### ISSUE TITLE
[Bug] Correct printing of Parameters object

### ISSUE THREAD

**Issue by mibaumgartner** [delira-dev/delira#113]
**Description**
`Parameters` objects are not printed correctly. They are printed like they are empty, even if they contain information.

**Comment by justusschock** [comment]
I cannot reproduce this on latest master. I tried with a very simple snippet:

```python
from delira.training import Parameters
params = Parameters(fixed_params={"model": 5})
print(params)
```

gives me 
```
Parameters:
	fixed = {
    "model": 5
}
	variable = {
    "model": {},
    "training": {}
}
```
which is correct and I get the same results by `print(str(params))`

**Comment by mibaumgartner** [comment]
Can not reproduce it myself :/ Closing this for now, sorry.
