### ISSUE TITLE
[Bug] Predictor caches results of validation

### ISSUE THREAD

**Issue by mibaumgartner** [delira-dev/delira#129]
**Description**
`Predictor` caches the predictions which results in very high memory usage when training segmentation networks and does not fit very well with lazy datasets.

https://github.com/justusschock/delira/blob/9d49560340edd08857262c42b55bd6342c46a0d0/delira/training/predictor.py#L254

**Comment by justusschock** [comment]
We should be able to avoid this, by specifying the [`lazy_gen`](https://github.com/justusschock/delira/blob/9d49560340edd08857262c42b55bd6342c46a0d0/delira/training/predictor.py#L142) to True, factor out the [`convert_to_dict`](https://github.com/justusschock/delira/blob/9d49560340edd08857262c42b55bd6342c46a0d0/delira/training/predictor.py#L269) and [`concatenate_dict_items`](https://github.com/justusschock/delira/blob/9d49560340edd08857262c42b55bd6342c46a0d0/delira/training/predictor.py#L317) functions and call them only on the metrics only (by caching only metrics and no more predictions). I'll give this a try tomorrow
