### ISSUE TITLE
[FeatureRequest] Make `Predictor` in experiment interchangeable  

### ISSUE THREAD

**Issue by mibaumgartner** [delira-dev/delira#131]
**Description**
Make the `Predictor` in `experiment._setup_test` interchangeable so additional functionality can be added more easily. 

**Proposal**
Add additional argument to change `Predictor`. 

Solution could look like:
```python
    def _setup_test(self, params, model, convert_batch_to_npy_fn, prepare_batch_fn, predictor_cls=Predictor, **kwargs):
        predictor = predictor_cls(
            model=model, key_mapping=self.key_mapping,
            convert_batch_to_npy_fn=convert_batch_to_npy_fn,
            prepare_batch_fn=prepare_batch_fn, **kwargs)
        return predictor
```

**Comment by justusschock** [comment]
I'd prefer a default argument of `None` here, which falls back to the basic predictor (or `self.predictor_cls` if we want to introduce this as class attribute`)
