### ISSUE TITLE
[FeatureRequest] Additional documentation for `calc_metric`

### ISSUE THREAD

**Issue by mibaumgartner** [delira-dev/delira#132]
**Description**
Additional documentation for `calc_metric` arguments. `metric_keys` needs some more explanation inside the trainer:
https://github.com/justusschock/delira/blob/9d49560340edd08857262c42b55bd6342c46a0d0/delira/training/base_trainer.py#L109-L112 
The description in `experiment.test` is more useful :) 
https://github.com/justusschock/delira/blob/9d49560340edd08857262c42b55bd6342c46a0d0/delira/training/experiment.py#L364-L368

Maybe, we should move some of the more important arguments + docs from the trainer to the `experiment.run` function, so it is not necessary to search for docs at two places?

What do you think @justusschock @haarburger  @ORippler ?

**Comment by justusschock** [comment]
The problem with this approach is, that the trainer class is exchangeable, which might result in wrong docs. This is, why there are only the essential arguments documented and the other ones go via `kwargs`
