### ISSUE TITLE
[Bug] train/test_kwargs emptied during BaseExperiment.kfold

### ISSUE THREAD

**Issue by ORippler** [delira-dev/delira#144]
**Description**
During BaseExperiment.kfold, train/test_kwargs are emptied during BaseExperiment.kfold.
Reason is, that [Datamanger.update_state_from_dict](https://github.com/justusschock/delira/blob/master/delira/data_loading/data_manager.py#L406) is called [multiple times](https://github.com/justusschock/delira/blob/master/delira/training/experiment.py#L550).

Inside the function, elements are removed from the input state_dict via .pop. Therefore, train/test_kwargs are emptied during the first update.

Possible solutions: Either pass a copy of train/test_kwargs as input or refrain from altering the input dict inside Datamanager.update_state_from_dict.

**Comment by justusschock** [comment]
I'd prefer to pass copies, since we cannot guarantee any behavior for subclasses
