### ISSUE TITLE
[Bug] Memoryleak in Predictor

### ISSUE THREAD

**Issue by cwern1** [delira-dev/delira#156]
**Description**
Using `Predictor` class leads to a memory leak when inferring with 2D slices on a 2D U-Net.

**Environment**
* OS: Ubuntu 18.04
* Python version: 3.7
* `delira` version 0.4.0
* How did you install `delira`? pip

**Reproduction**
I'm feeding single samples with `batch_size = 1` through the `Predictor`, aggregate them and convert to `SimpleITK`. You can find a script that reproduces the error [here](https://github.com/haarburger/breast-segmentation/blob/master/experiments/inference.py)

**Comment by justusschock** [comment]
I tried to simplify your code a bit for debugging and removed any non-delira stuff

```
from delira.models import AbstractPyTorchNetwork
from delira.data_loading import AbstractDataset, BaseDataManager
import torch
import numpy as np
from delira.training import Predictor
from functools import partial


class DummyModel(AbstractPyTorchNetwork):

    def forward(self, x):
        return {"pred": x}

    @staticmethod
    def prepare_batch(batch: dict, input_device, output_device):
        return {"data": torch.from_numpy(batch["data"]).to(torch.float)}

    
class DummyModel2(DummyModel):
    def __init__(self):
        super().__init__()
        self._conv = torch.nn.Conv2d(1, 1, 3, 1, 1)

    def forward(self, x):
        return super().forward(self._conv(x))


class DummyDset(AbstractDataset):
    def __init__(self, length):
        super().__init__(None, None)
        self.length = length

    def __getitem__(self, item):
        return {"data": np.random.rand(1, 512, 512)}

    def get_sample_from_index(self, index):
        return self[index]

    def __len__(self):
        return self.length


if __name__ == '__main__':
    model = DummyModel()
    dset = DummyDset(10000)
    dmgr = BaseDataManager(dset, 1, 1, None)
    with torch.no_grad():
        predictor = Predictor(model, key_mapping={"x": "data"},
                              prepare_batch_fn=partial(model.prepare_batch,
                                                       input_device="cpu",
                                                       output_device="cpu"))

        for idx, pred in enumerate(predictor.predict_data_mgr(dmgr)):
            print(pred)
            print(idx)
```
I must say, that I could not observe any suspicious increase of memory here after everything was initialized (neither for `DummyModel`, which does nothing, nor for `DummyModel2`, which does a dummy convolution). Also, we use the predictor internally during training. If there was a memory leak, we would run OOM quite often I guess.

Can you try to switch to latest master?

**Comment by justusschock** [comment]
Did you try it? Were you still seeing a memory issue?

**Comment by cwern1** [comment]
Can't reproduce the problem after switching to the latest master.
