### ISSUE TITLE
ImportError: cannot import name 'PytorchVisdomLogger'

### ISSUE THREAD

**Issue by aivyon** [delira-dev/delira#159]
**Description**
from trixi.logger import PytorchVisdomLogger
ImportError: cannot import name 'PytorchVisdomLogger' from 'trixi.logger' (C:\Users\korrine\AppData\Local\Continuum\anaconda3\envs\pytorch_new\lib\site-packages\trixi\logger\__init__.py)

Process finished with exit code 1

![image](https://user-images.githubusercontent.com/50579056/60765246-ea244300-a09f-11e9-8b84-fccc842e6fc5.png)
![image](https://user-images.githubusercontent.com/50579056/60765251-06c07b00-a0a0-11e9-8b8f-95e1b16b831b.png)

**Environment**windows
* OS:
* Python version: 3.7
* `delira` version : 0.3.2
* How did you install `delira`? [ pip | source | conda | docker ]
* Machine Specs:
* Minimal working Example:

**Comment by justusschock** [comment]
did you install `delira[torch]` or just `delira`?

I'm asking because if you do `pip install delira`, we only have `trixi-slim` as a dependency (which also gets imported as `trixi`) and `trixi-slim` does not have a pytorch dependency and thus no pytorch loggers available. If you do `pip install delira[torch]` we install `trixi` as dependency and thus the logger should be available.

**Comment by aivyon** [comment]
Yes I did pip install delira[torch]

**Comment by aivyon** [comment]
Still 
 File "train_single_shapenet.py", line 24, in train_shapenet
    from trixi.logger import PytorchVisdomLogger
ImportError: cannot import name 'PytorchVisdomLogger' from 'trixi.logger' (C:\Users\korrine\AppData\Local\Continuum\anaconda3\envs\pytorch_new\lib\site-packages
\trixi\logger\__init__.py)

**Comment by aivyon** [comment]
tried to 
git clone https://github.com/MIC-DKFZ/trixi.git
cd trixi
pip install -e .
but now it need newer version of torch:


Collecting torch>=1.1.0 (from trixi==0.1.2.2)
  ERROR: Could not find a version that satisfies the requirement torch>=1.1.0 (from trixi==0.1.2.2) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=1.1.0 (from trixi==0.1.2.2)

**Comment by justusschock** [comment]
The problem is, you're running Windows, installing pytorch on Windows is different. Have a look at [the official pytorch website](https://pytorch.org)

**Comment by aivyon** [comment]
Yes I installed pytorch according to official site . everything works fine. Just this problem with 
PytorchVisdomLogger' from 'trixi.logger' . 
Everything was supposed to be installed with pip install delira[torch]? 
but it didn't for some reason?

**Comment by justusschock** [comment]
I don't know what did go wrong with your installation, the import works fine for me.

Can you run the following script and give me its outputs?

```python
import trixi
print("Trixi Version: " + trixi.__version__)
import torch
print("Torch version: " + torch.__version__)
import delira
print("Delira version: " + delira.__version__)
import sys
print("OS: " + sys.platform)
print("Python Version: " + sys.version)
```
For you to compare: the outputs it gives me (on my windows machine) with the latest stable version of `delira` and `pytorch` are:

> Trixi Version: 0.1.2.2
> Torch version: 1.1.0
> Delira version: 0.4.0
> OS: win32
> Python Version: 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]

**Comment by aivyon** [comment]
I got :
Trixi Version: 0.1.2.1
Torch version: 1.0.1
Delira version: 0.3.3
OS: win32
Python Version: 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]

**Comment by justusschock** [comment]
Can you try to install the newer trixi? There were some reported issues with their dependencies, as you can see [here](https://github.com/MIC-DKFZ/trixi/issues/15) and [here](https://github.com/MIC-DKFZ/trixi/issues/18). What should probably fix your issue:
`pip uninstall -q pytorch trixi && pip install pytorch==1.1.0 trixi==0.1.2.2`

**Comment by justusschock** [comment]
Did this fix your issue?

**Comment by aivyon** [comment]
Yes it did . Thank you!
I am trying to deal with the training now. Thank you.
