### ISSUE TITLE
code version details and dependicy version

### ISSUE THREAD

**Issue by poorneshwaran** [delira-dev/delira#163]
I tried to run your code.. i got multiple error while running different times  like cuda out of memory , requires 800 gb and size of tensor are mismatch  and softmax is not used..

what version will process the code which you provide in notebooks and docs.
so please share apex version and delira version and python version.

I used conda pytorch and python 3.6 and delira 0.4.0

**Comment by justusschock** [comment]
The code worked for me with delira 0.3.2 (and should also work with 0.4.0). I don't know the APEX version, since I executed it without Apex. The python version shouldn't matter as long as it is greater or equal to 3.5.

However, we have noted some memory issues and fixed them on latest master.
