### ISSUE TITLE
[FeatureRequest] New Config

### ISSUE THREAD

**Issue by mibaumgartner** [delira-dev/delira#169]
New config class with improved functionality:

- [x] New model and training parameter handling (parameters are defined inside `DeliraConfig` by keys `fixed_model`, `fixed_training`, `variable_model`, `variable_training`)
- [x] New functions to read needed parameters (e.g. `get_fixed`, `get_variable`)
- [ ] New encoder/decoder functions with yaml and json support (including support to encode/decode complex classes/modules/methods)
- [x] Save additional settings in `DeliraConfig` (timestamp, delira version)
- [x] Warning for integer keys (because of ambiguous decoding of nested string access)
- [ ] Update Trainers to use new `DeliraConfig`

Are there any features I missed? @justusschock

**Comment by justusschock** [comment]
I think that's all for now

**Comment by justusschock** [comment]
Regarding the warning for integer keys: we should do that for all non-string keys I guess, because with floats this might be the same

**Comment by justusschock** [comment]
The only thing left here is proper encoding/decoding, logging, to check, whether the copy functions work out of the box and add some testcases/docstrings

**Comment by mibaumgartner** [comment]
Introduced with https://github.com/delira-dev/delira/pull/206
