### ISSUE TITLE
[Bug] Checkpoints will not be saved

### ISSUE THREAD

**Issue by gedoensmax** [delira-dev/delira#183]
**Description**
If a checkpoint frequency is set it is expected that a new checkpoint is created at suiting checkpoints. 
Due to wrong indent in `BaseNetworkTrainer.train` at line 488 this is no longer happening.
In addition wouldn't it make sense to write a checkpoint at the end of training ? Not regarding checkpoint frequency or best checkpoint. (`TfNetworkTrainer._at_training_end`)

**Comment by mibaumgartner** [comment]
The indentation is fixed in PR https://github.com/delira-dev/delira/pull/182 which needs some additions regarding the notebooks. I like the idea of saving the last model (I would add this to the basetrainer instead of adding it to a specific trainer) :)

**Comment by mibaumgartner** [comment]
I created a new Issue for the feature requests and fixed in the bug in a separate PR to move things forward.
