### ISSUE TITLE
[Bug] Poor augmentation performance when not in debug mode

### ISSUE THREAD

**Issue by cwern1** [delira-dev/delira#194]
**Description**
When training using `n_process=4` the performance is _worse_ than when using `delira` debug mode. This also happens when setting `n_process=1`. 

In my example I get ~1.3s/batch with `n_process=4` and 2 batch/s in debug mode. With multithreading working properly I would expect something like 4 batch/s at least.

The problem occurs with batchgenerators versions 0.19.3. I also tested against 0.18.2, which resulted in the same problem.

**Environment**
* OS: Ubuntu 18.04
* Python version: 3.7
* `delira` version: `master`
* How did you install `delira`? source

**Reproduction**
The script needed for reproduction is in my private repo, but @mibaumgartner and @justusschock have access.
```bash
git checkout https://github.com/haarburger/multi-scale-curriculum-prototype
cd multi-scale-curriculum
pip install -e . # delira is the only dependency
python experiments/mri/exec_wic.py -cp experiments/mri/config_debug_wic.yml # depends on files at LfB filesrv
```

**Comment by justusschock** [comment]
This is a known issue, and we already started working on it (see PR #154 ). The issue lies within the fact, that we had to hack batchgenerators a bit for our sampling and the mentioned PR resolves this issue. It is almost good to go, only one sampler is not yet working the way it is expected to.
