### ISSUE TITLE
[Question] Metric calculation

### ISSUE THREAD

**Issue by gedoensmax** [delira-dev/delira#195]
I suspect that we are feeding values wrong at the [predictor](https://github.com/delira-dev/delira/blob/c5f3598883875abfa8a4cab0e3f302007ce1136a/delira/training/predictor.py#L629) to calculate metrics. As I am debugging something in there i noticed that we provide labels as predictions for the case sklearn metrics are used. I know for a lot of metrics this is not a problem but don't we have a few cases where this is wrong (for example SSIM) ?

**Comment by justusschock** [comment]
You are right, we should flip these values. I did not take care of it, since this should be identical for most metrics, but did not pay attention to the fact, that it isn't for all of them.

I think the easiest way to achieve this is to flip all the default values

**Comment by gedoensmax** [comment]
Ok i would include this in #172
