### ISSUE TITLE
[Question] Timestamp in save path

### ISSUE THREAD

**Issue by gedoensmax** [delira-dev/delira#197]
Don't you think we can get rid of the timestamp in save path ? 
It will make automatic reload more straight forward and it is already warned that checkpoints will be [overwritten](https://github.com/delira-dev/delira/blob/93498accf96b390a24bb5c386874cab6f7cb6fbb/delira/training/base_trainer.py#L146).
At the moment a new save path will  be created with a new timestamp and nothing will be overwritten.

**Comment by justusschock** [comment]
Yeah, we can for sure do this. Would you do this? (Probably best done in a separate function)

**Comment by gedoensmax** [comment]
I will look into it. I thought it would be possible to just delete one line of code where this timestamp is generated.

**Comment by justusschock** [comment]
No, we should probably change this to the following behavior: If the folder still exists append a 1 to it. if this foldder exists, exchange the 1 by a 2 and so on.

**Comment by gedoensmax** [comment]
I will include this in #172 ok ?

**Comment by justusschock** [comment]
Actually I discussed with @mibaumgartner and we decided, that we want to keep the PRs cleaner and more related to their original topic. So a new PR would be better

**Comment by gedoensmax** [comment]
Ok so i will close this one and open a new PR.
