### ISSUE TITLE
[FeatureRequest] Dataset preview

### ISSUE THREAD

**Issue by gedoensmax** [delira-dev/delira#198]
What do you think about adding a preview function to the [BaseDataManger](https://github.com/delira-dev/delira/blob/3b7794be9787fc0b99133e4201a6928708829ad2/delira/data_loading/data_manager.py#L271) which could be named `plot_batch`.
It is often wanted to have a look at one batch of training especially for debugging purposes or if you want to *debug* your dataset.

**Comment by justusschock** [comment]
I am strongly against this. This would assume, that our repo is for vision tasks only (which simply is not the case right now). But you can maybe add this to https://github.com/delira-dev/contrib

**Comment by gedoensmax** [comment]
Oh yes good point did not consider that.
