### ISSUE TITLE
[Bug] `PTNetworkTrainer.predict` drops last elements of `batchgen`

### ISSUE THREAD

**Issue by ORippler** [delira-dev/delira#31]
**Description**
[This condition](https://github.com/justusschock/delira/blob/master/delira/training/pytorch_trainer.py#L498) is never fulfilled, and therefore the last elements of `batchgen` are dropped.
If `batch_size` is modified, internal `orig_batch_size` is required to correctly generate averages by ceiling.

**Environment**
* OS: Ubuntu 18.04
* Python version: 3.6
* `delira` version: 0.2.0-beta.1
* How did you install `delira`? [source]

**Reproduction**
Run MNIST Classification example

**Additional context**

**Comment by justusschock** [comment]
You are right, probably the condition must be moved above the outer if-Statement.
I will test this tomorrow

**Comment by justusschock** [comment]
fixed by 6a502395e4b8a81db57a64a72fdc13583e893a1d
