### ISSUE TITLE
Tf Integration

### ISSUE THREAD

**Issue by justusschock** [delira-dev/delira#45]
Currently working on this

**Comment by justusschock** [comment]
Currently todo:

- [x] Rebase from master and refactor accordingly (e.g. #6)
- [x] Add docstrings similar to the existing ones ([Numpy style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html))
- [x] Add tests with pytest (and ensure tests are skipped if not enough RAM etc.); examples can be found at the [currently implemented tests](https://github.com/justusschock/delira/tree/master/tests)
- [x] Add a requirements file for all tensorflow requirements similar to the [torch requirements file](https://github.com/justusschock/delira/blob/master/requirements_extra_torch.txt)
- [x] Register it as backend in [`setup.py`](https://github.com/justusschock/delira/blob/master/setup.py) and [`__init__.py`](https://github.com/justusschock/delira/blob/master/delira/__init__.py)
- [ ] maybe: Combine classes with same purpose but different backend in one file for simplicity (esp. in [models](https://github.com/justusschock/delira/blob/master/delira/models) and [training](https://github.com/justusschock/delira/blob/master/delira/training))

**Comment by ORippler** [comment]
tests should pass once [tensorboard logging is released in trixi](https://github.com/MIC-DKFZ/trixi/issues/12)
