### ISSUE TITLE
[FeatureRequest] Add logging Frequency during training

### ISSUE THREAD

**Issue by ORippler** [delira-dev/delira#48]
**Description**
Provide means to specify logging Frequency during training. For Visdom, all logging results are kept in memory (risking OOM), and with tensorboardlogger, disk I/O may bottleneck training otherwise.

**Proposal**
There are different ways to tackle this. One could be to utilize `CombinedLogger` from `trixi`. However, I'm unsure whether `CombinedLogger` allows for logging frequencies assigned per logged object (e.g. Scalars every iteration and images every Nth iteration), which is a feature I would like to have.

**Additional context**
Solve before implement logging frequencies as part of #47

**Comment by justusschock** [comment]
I'd like to address this, once #139 is done, since we can then introduce a logging frequency on our own (without having to hack `trixi` anymore)
