### ISSUE TITLE
[FeatureRequest] kwargs for models

### ISSUE THREAD

**Issue by amoriz512** [delira-dev/delira#59]
The previous versions of delira had a kwargs argument for models. This was quite useful, it would be great if it would be available in the version of delira as well.

**Comment by cwern1** [comment]
Why was it removed in the first place @justusschock ?

**Comment by justusschock** [comment]
It was removed due to the merge of `model_kwargs` and `Hyperparameters`. This was the easiest way to implement this. I'll have a look at it and try to find a way to re-introduce it @haarburger .

**Comment by justusschock** [comment]
This should probably be done as part of #46
