### ISSUE TITLE
[Bug] Mac OS X: Backend for TF not found

### ISSUE THREAD

**Issue by gedoensmax** [delira-dev/delira#61]
**Description**
I tried installing delira with and without backend to a conda environment which has an already installed Tensorflow 1.12 in it. I get this error when executing one of the tests for example:
```
python3 delira/tests/models/test_models_tf.py 
Traceback (most recent call last):
  File "/Users/mmueller/Documents/03_Programmieren/02_machine_learning/installation/lfb/delira/tests/models/test_models_tf.py", line 2, in <module>
    if "tf" in os.environ["DELIRA_BACKEND"]:
  File "/Users/mmueller/miniconda3/envs/ml/lib/python3.7/os.py", line 678, in getitem
    raise KeyError(key) from None
KeyError: 'DELIRA_BACKEND'
```
I am not sure if i have to install any Backend in addition to a normal tensorflow installation. In this case it may be added to the Readme. Thankful for any help!

**Environment**
* OS: Mac OS X 10.13.6
* Python version: 3.7.2
* delira version: 0.3.0

**Reproduction**
I installed Tensorflow 1.12 from this [git](https://github.com/TomHeaven/tensorflow-osx-build) with this [instruction](https://gist.github.com/antoniopioricciardi/240921b16e32dcc67a779e11dfaade1d).
Now it is listed in conda as tensowrflow but not as tensorflow-gpu although GPU support works, which i think may be the error.

**Additional context**
I already tried just changing the requirement to just tensorflow.

**Comment by justusschock** [comment]
Thank you for report. Unfortunately, I don't have a Mac myself, so I need some of my colleagues to have a look at this.

Usually this should not happen, because both packages get installed as tensorflow and we simply try to import it once to determine the available backends...

**Comment by justusschock** [comment]
Have you tried, if it works installing it all together?

Did you install TensorFlow before or after installing delira?

**Comment by gedoensmax** [comment]
Tensorflow with gpu is not supported on mac os so this is not really a chance. If you want to have a look just drop by in room 115 i will be free till 11:30 am.

**Comment by gedoensmax** [comment]
Should actually work when installing with `pip install -e . ` in an environment which already has tf in it.

**Comment by cwern1** [comment]
Did that do the trick?

**Comment by gedoensmax** [comment]
I think so but i have not tested a working example because i just started coding with delira but i will report back if there are any more errors while running.
