### ISSUE TITLE
[FeatureRequest] Dataset refactoring to more general version

### ISSUE THREAD

**Issue by mibaumgartner** [delira-dev/delira#74]
**Description**
Some of the interfaces of the implemented datasets are somtimes to specific. It would be great to create more general datasets which don't impose any constraints to the user.

**Proposal**
`AbstractDataset` should only need a `load_fn` and a `data_path` (remove img-, label-extensions)

`BaseCacheDataset` should only need a `load_fn` and a `data_path`. Should be able to handle a single `data_path` where it searches the respective folder for sub directories/files and calls `load_fn` for all of them. Should be able to handle a list of paths and call `load_fn` for all of them. (Could be implemented in a single class or in two separate classes.)

`BaseLazyDataset`: same criterion as `BaseCacheDataset`

In order to replicate the current ability to load multiple extensions into a single sample an improved loading function would be helpful.

**Comment by justusschock** [comment]
cc @ORippler 

@mibaumgartner : I don't have capacities to work on this, but I#d review, if you can do the coding part.

**Comment by mibaumgartner** [comment]
I'm going to work on it this weekend. Should I add any other feature which is not listed above?

**Comment by justusschock** [comment]
I think it'd be best, if you prototype a first draft, and if I see anything obvious I'll add this as my review and /or add it myself

**Comment by justusschock** [comment]
done by #88
