### ISSUE TITLE
[Bug] notebook "tutorial_delira" failed

### ISSUE THREAD

**Issue by SouthMemory** [delira-dev/delira#87]
**Description**
run https://github.com/justusschock/delira/blob/master/notebooks/tutorial_delira.ipynb
failure:
1, " Experiment" : 
ValueError: all the input array dimensions except for the concatenation axis must match exactly
2, "Logging::
nothing show nowhere. 

run https://github.com/justusschock/delira/blob/master/notebooks/segmentation_2d_pytorch.ipynb
"logger.info("Init Experiment")", nothing shows nowhere. 

Can you please check this notebook again?

**Comment by justusschock** [comment]
I'll investigate into this later, but the first thing I can tell you is regarding the logging:

The notebook only uses a Visdomlogger and simple texts are not logged to visdom. To be shown to visdom, your logged value must be a nested dict with keys mapping to a function of your Logger.

If you additionally want to log to your console, you have to use an additional Handler (probably `logging.StreamHandler`)

**Comment by SouthMemory** [comment]
Thanks a lot for your answer, Mr justusschock

I have a confusion here:

- [ ] delira/training/experiment.py:
- [ ] line 25 : logger = logging.getLogger(__name__)
- [ ] line 532 : logger.warning("Save Path %s already exists")

Are these two logger the same thing ?  what's the reason?
How to exactly code it so "Save Path %s already exists" can be logged to visdom ?

I am new to logging ,  maybe my question is kind of naive, but I have studied this problem several days, and still no clue.

Please, Thanks!

**Comment by justusschock** [comment]
Well you can log it as text to visdom although I don't recommend this.

You'd have to log something like 
```
{"text": {"text": YOUR STRING HERE"}} 
```
But I am not really sure about the Syntax right now (I'll check on this and report back). 

What I'd recommend you is to add an additional `StreamHandler` to the handlers in the basicconfig which should make everything being also logged to terminal. 

EDIT: For the visdom version, you could have a look on how it is handled in [the experiment](https://github.com/justusschock/delira/blob/master/delira/training/experiment.py#L551)

**Comment by SouthMemory** [comment]
Maybe I should wait for your new doc.
Thanks

**Comment by justusschock** [comment]
Sorry for the inconvenience, we are currently refactoring the trainer (in #66 ) and once this is done, I'll update the notebooks. But I'll look into the current problem.

**Comment by SouthMemory** [comment]
Thanks for your great work!
 Looking forward to your complete.
